 export const arrayWines: any = [{
    id: 1,
    name: "nombre Vino",
    description: "Descripcion del vino",
    category: "vino",
    image: "/vinoCard.jpg",
    },
    {
    id: 2,
    name: "nombre Gin",
    description: "Descripcion del Gin",
    category: "gin",
    image: "/ginCard.png",
    },
    {
    id: 3,
    name: "nombre Gin",
    description: "Descripcion del Gin",
    category: "gin",
    image: "/ginCard.png",
    },
    {
    id: 5,
    name: "nombre Gin",
    description: "Descripcion del Gin",
    category: "gin",
    image: "/ginCard.png",
    },
    {
    id: 6,
    name: "nombre Gin",
    description: "Descripcion del Gin",
    category: "gin",
    image: "/ginCard.png",
    },
    {
    id: 7,
    name: "nombre Gin",
    description: "Descripcion del Gin",
    category: "gin",
    image: "/ginCard.png",
    },
    {
    id: 4,
    name: "nombre Licor",
    description: "Descripcion del Licor",
    category: "licor",
    image: "/licorCard.png",
}];